# Generated by Django 2.2.11 on 2020-03-10 13:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('ex_dividend_date', models.DateField()),
                ('value_per_stock', models.DecimalField(decimal_places=9, max_digits=15)),
                ('full_value', models.DecimalField(decimal_places=9, max_digits=15)),
                ('yield_per_stock', models.DecimalField(decimal_places=9, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=120)),
                ('short_name', models.CharField(max_length=10)),
                ('ammount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price_for_one_stock', models.DecimalField(decimal_places=9, max_digits=15)),
                ('price_for_stocks', models.DecimalField(decimal_places=9, max_digits=19)),
                ('divident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_wallet.Dividend')),
            ],
        ),
        migrations.CreateModel(
            name='StockWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('total_profit', models.DecimalField(decimal_places=9, max_digits=28)),
                ('is_private', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_wallet.StockRecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
