# Generated by Django 2.2.11 on 2020-03-14 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_wallet', '0003_auto_20200314_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrecord',
            name='divident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_wallet.Dividend'),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='price_for_stocks',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='stockwallet',
            name='total_profit',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=28, null=True),
        ),
    ]
