# Generated by Django 2.2.11 on 2020-03-14 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_wallet', '0004_auto_20200314_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockrecord',
            name='divident',
        ),
        migrations.AddField(
            model_name='dividend',
            name='stockrecord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_wallet.StockRecord'),
        ),
    ]
