# Generated by Django 2.2.11 on 2020-03-18 19:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock_wallet', '0005_auto_20200314_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=120)),
                ('short_name', models.CharField(max_length=10)),
                ('ammount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price_for_one_stock', models.DecimalField(decimal_places=9, max_digits=15)),
                ('price_for_stocks', models.DecimalField(blank=True, decimal_places=9, max_digits=19, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SumRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=120, null=True)),
                ('short_name', models.CharField(blank=True, max_length=10, null=True)),
                ('ammount', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_for_one_stock', models.DecimalField(blank=True, decimal_places=9, max_digits=15, null=True)),
                ('price_for_stocks', models.DecimalField(blank=True, decimal_places=9, max_digits=19, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dividend',
            name='stockrecord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_wallet.Record'),
        ),
        migrations.RenameModel(
            old_name='StockWallet',
            new_name='Wallet',
        ),
        migrations.DeleteModel(
            name='StockRecord',
        ),
        migrations.AddField(
            model_name='sumrecords',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_wallet.Wallet'),
        ),
        migrations.AddField(
            model_name='record',
            name='stock_records',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_wallet.SumRecords'),
        ),
        migrations.AddField(
            model_name='record',
            name='stock_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_wallet.Wallet'),
        ),
    ]
