# Generated by Django 2.2.11 on 2020-03-18 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_wallet', '0007_remove_record_stock_records'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='stock_wallet',
            new_name='wallet',
        ),
    ]
