# Generated by Django 2.2.11 on 2020-03-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_wallet', '0012_auto_20200319_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='cash',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=28, null=True),
        ),
    ]
