# Generated by Django 2.2.11 on 2020-03-24 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock_wallet', '0015_auto_20200323_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividend',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dividend',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dividend',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='purchasedshare',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
