# Generated by Django 2.2.11 on 2020-04-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_wallet', '0016_auto_20200324_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='cash',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=28),
        ),
    ]
