# Generated by Django 2.2.11 on 2020-04-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_wallet', '0018_auto_20200401_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedshare',
            old_name='share_price',
            new_name='current_price',
        ),
    ]
