# Generated by Django 2.2.11 on 2020-04-05 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_wallet', '0022_auto_20200405_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedshare',
            old_name='company',
            new_name='company_name',
        ),
    ]
