# Generated by Django 2.2.11 on 2020-04-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_wallet', '0023_auto_20200405_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedshare',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
